'use client';
import Link from 'next/link';
import{useMemo,useState}from'react';
import{ResponsiveContainer,AreaChart,Area,XAxis,YAxis,CartesianGrid,Tooltip}from'recharts';
import{ecode,ename,code,name,fmt,fm,pct,toneCls,price,cpct,mvb,lots,chartRows,ddate,num,region,fav}from'./mobileV86Utils';
type Tab='overview'|'live'|'operation'|'holdings'|'basic';
const back=()=>{if(typeof window!=='undefined'&&window.history.length>1)window.history.back();else location.href='/etfs'};
function Header({c,nm,type}:{c:string,nm:string,type:'etf'|'stock'}){return <header className="v86-dh"><button onClick={back}>‹</button><div><b>{c}</b><span>{nm}</span></div><button onClick={()=>fav(c,nm,type)}>☆</button></header>}
function Chart({rows,red=true}:any){return rows.length?<div className="v86-chart"><ResponsiveContainer width="100%" height={190}><AreaChart data={rows}><CartesianGrid strokeDasharray="4 4" vertical={false}/><XAxis dataKey="date" tickFormatter={(v)=>String(v).slice(5,10)} minTickGap={18}/><YAxis width={38} domain={['auto','auto']}/><Tooltip/><Area type="monotone" dataKey="value" stroke={red?'#df555d':'#27a575'} fill={red?'#fff1f2':'#ecfdf5'} strokeWidth={2.2}/></AreaChart></ResponsiveContainer></div>:<div className="v86-empty">尚無趨勢資料</div>}
function HRows({rows}:any){const a=Array.isArray(rows)?rows:[];return <section className="v86-list">{a.slice(0,120).map((r:any,i:number)=><Link key={(code(r)||ecode(r))+i} href={`/stock/${code(r)}?from=etf`} className="v86-hrow"><div><b>{name(r)}</b><span>{code(r)}</span></div><div><b>{fm(mvb(r))} 億</b><span>{fm(lots(r))} 張</span></div><div><b>{fm(r.weight,2)}%</b></div><div><b>{fm(price(r),1)}</b><span className={toneCls(cpct(r))}>{pct(cpct(r),2)}</span></div></Link>)}</section>}
export default function EtfDetailClient(props:any){const data=props?.data||props,q=data?.quote||data?.etf||data;const c=ecode(q)||data?.code||data?.etf_code,nm=ename(q)||data?.name||data?.etf_name;const[tab,setTab]=useState<Tab>('overview');const holdings=data?.currentRows||data?.current_rows||data?.holdings||data?.rows||[];const changes=data?.changes||data?.operationRows||data?.operation_rows||[];const ch=useMemo(()=>chartRows(data),[data]);return <main className="v86-detail"><Header c={c} nm={nm} type="etf"/><nav className="v86-tabs">{([['overview','總覽'],['live','即時'],['operation','操作日報'],['holdings','成分股'],['basic','基本']] as any).map(([k,t]:any)=><button onClick={()=>setTab(k)} className={tab===k?'on':''} key={k}>{t}</button>)}</nav>{tab==='overview'&&<section><div className="v86-kpis"><div><span>股價</span><b className={toneCls(cpct(q))}>{fm(price(q),2)}</b><small>{pct(cpct(q),2)}</small></div><div><span>成立以來</span><b>{pct(q?.total_return??q?.since_inception_return,1)}</b><small>報酬</small></div><div><span>今日淨流動</span><b>{fm(q?.net_flow_billion??q?.flow_billion,1)} 億</b><small>估算</small></div><div><span>資料狀態</span><b className={holdings?.length?'v86-green':'v86-red'}>{holdings?.length?'完整':'待補'}</b><small>股價/成分股/歷史</small></div></div><h2>淨值 / 股價走勢</h2><Chart rows={ch} red={num(cpct(q),0)>=0}/><h2>前五大持股</h2><HRows rows={holdings}/></section>}{tab==='live'&&<section><div className="v86-kpis"><div><span>股價</span><b className={toneCls(cpct(q))}>{fm(price(q),2)}</b><small>{pct(cpct(q),2)}</small></div><div><span>成交量</span><b>{fm(q?.volume)}</b><small>{fm(q?.amount_billion,1)} 億</small></div></div><div className="v86-info"><p><span>更新時間</span><b>{String(q?.updated_at||ddate(data)||'-').slice(0,19).replace('T',' ')}</b></p></div></section>}{tab==='operation'&&<section><div className="v86-pills"><span className="新增">異動 {changes.length}</span></div><HRows rows={changes}/></section>}{tab==='holdings'&&<HRows rows={holdings}/>} {tab==='basic'&&<section className="v86-info"><p><span>資產規模</span><b>{fm(q?.aum_billion??q?.fund_size_billion,1)} 億</b></p><p><span>內扣費用</span><b>{fm(q?.expense_ratio,2)}%</b></p><p><span>投資區域</span><b>{region(q)}</b></p><p><span>成立日</span><b>{q?.inception_date||q?.listing_date||'-'}</b></p></section>}</main>}
