'use client';
import Link from 'next/link';
import {useMemo,useState} from 'react';
import {ecode,ename,fm,pct,toneCls,price,cpct,num,region,ddate} from './mobileV86Utils';
type T='live'|'return'|'basic';
const amt=(r:any)=>{const x=Number(r?.amount_billion??r?.turnover_billion??r?.trading_amount_billion);if(Number.isFinite(x))return x;const y=Number(r?.amount??r?.turnover??r?.trading_amount);return Number.isFinite(y)?y/100000000:NaN};
const aum=(r:any)=>r?.aum_billion??r?.fund_size_billion??r?.asset_billion??r?.scale_billion;const r1w=(r:any)=>r?.one_week_return??r?.return_1w??r?.week_return;const tr=(r:any)=>r?.total_return??r?.since_inception_return??r?.return_since_inception??r?.ytd_return;const fee=(r:any)=>r?.expense_ratio??r?.fee??r?.management_fee??r?.total_fee;
function Card({r,tab}:any){const c=ecode(r),p=cpct(r);return <Link href={`/etf/${c}?from=etfs`} className="v86-card"><i className={p>=0?'red':'green'}/><div><div className="v86-card-top"><h3>{c}<span>{ename(r)}</span></h3><strong>{fm(price(r),2)}<small className={toneCls(p)}>{pct(p,2)}</small></strong></div>{tab==='live'&&<p><span>成交量 <b>{fm(r?.volume??r?.trade_volume)}</b></span><span>成交金額 <b>{fm(amt(r),1)} 億</b></span><span>更新 <b>{String(ddate(r)||r?.updated_at||'-').slice(5,16).replace('T',' ')}</b></span></p>}{tab==='return'&&<p><span>1週報酬 <b className={toneCls(r1w(r))}>{pct(r1w(r),1)}</b></span><span>成立以來 <b className={toneCls(tr(r))}>{pct(tr(r),1)}</b></span><span>配息 <b>{r?.dividend_frequency||'-'}</b></span></p>}{tab==='basic'&&<p><span>資產規模 <b>{fm(aum(r))} 億</b></span><span>費用 <b>{Number.isFinite(Number(fee(r)))?fm(fee(r),2)+'%':'-'}</b></span><span>區域 <b>{region(r)}</b></span></p>}<div className="v86-badges"><span>股價 {Number.isFinite(Number(price(r)))?'✓':'-'}</span><span>成分股 {(r?.has_holding_data||r?.latest_holding_date||r?.latestHoldingDate)?'✓':'-'}</span><span>歷史 {(r?.has_price_history||r?.history_ready)?'✓':'-'}</span></div></div></Link>}
export default function EtfListClient(props:any){const rows:any[]=props?.rows||props?.data?.rows||props?.data||props?.etfs||[];const[tab,setTab]=useState<T>('live');const[q,setQ]=useState('');const sorted=useMemo(()=>{const f=(Array.isArray(rows)?rows:[]).filter(r=>`${ecode(r)} ${ename(r)}`.toLowerCase().includes(q.trim().toLowerCase()));return[...f].sort((a,b)=>tab==='return'?num(tr(b),-999)-num(tr(a),-999):tab==='basic'?num(aum(b),-999)-num(aum(a),-999):num(cpct(b),-999)-num(cpct(a),-999))},[rows,tab,q]);return <main className="page v86-page"><section className="v86-head"><div><h1>ETF 列表</h1><p>共 {sorted.length} 檔，每檔 ETF 可點進詳情。</p></div><div className="v86-mini"><button onClick={()=>setTab('live')} className={tab==='live'?'on':''}>即時</button><button onClick={()=>setTab('return')} className={tab==='return'?'on':''}>報酬</button><button onClick={()=>setTab('basic')} className={tab==='basic'?'on':''}>基本</button></div></section><input className="v86-search" value={q} onChange={e=>setQ(e.target.value)} placeholder="搜尋 ETF 或代號"/><section>{sorted.map((r,i)=><Card r={r} tab={tab} key={ecode(r)+i}/>)}</section></main>}
