'use client';
import Link from 'next/link';
import {useMemo,useState} from 'react';
import {code,name,fmt,fm,pct,toneCls,cpct,price,num,ddate} from './mobileV86Utils';
type S='新增'|'刪除'|'加碼'|'減碼';
const flow=(r:any)=>{const x=Number(r?.amount_billion??r?.flow_billion??r?.capital_flow_billion??r?.delta_amount_billion??r?.money_billion);if(Number.isFinite(x))return x;const y=Number(r?.amount??r?.flow_amount??r?.delta_amount??r?.market_value_change);if(Number.isFinite(y))return y/100000000;return num(r?.delta_shares??r?.shares_change??r?.change_lots,0)*num(price(r),0)*1000/100000000};
const addc=(r:any)=>num(r?.buy_etf_count??r?.add_etf_count??r?.etf_add_count??r?.positive_etf_count??r?.buy_count??r?.add_count,0);
const redc=(r:any)=>num(r?.sell_etf_count??r?.reduce_etf_count??r?.etf_reduce_count??r?.negative_etf_count??r?.sell_count??r?.reduce_count,0);
const st=(r:any):S=>{const s=String(r?.status||r?.action||r?.change_type||'');if(s.includes('新增'))return'新增';if(s.includes('刪'))return'刪除';if(s.includes('減'))return'減碼';if(s.includes('加'))return'加碼';const d=num(r?.delta_shares??r?.shares_change??r?.change_lots,0);return d<0?'減碼':d>0?'加碼':'加碼'};
function Focus({title,item,kind}:any){if(!item)return null;const c=code(item),p=cpct(item),f=flow(item);return <Link href={`/stock/${c}?from=signals`} className={`v86-focus ${kind}`}><b>{title}</b><div className="v86-focus-grid2"><div><h3>{name(item)} <span>{c}</span></h3><strong className={toneCls(p)}>{fm(price(item),1)} <small>{pct(p,2)}</small></strong></div><div><em>資金動向</em><i className={f>=0?'v86-red':'v86-green'}>{f>=0?'+':''}{fmt(f,1)} 億</i><em>多空共識</em><i>{addc(item)}:{redc(item)}</i></div></div></Link>}
export default function SignalsClient(props:any){const data=props?.data||props;const rows:any[]=data?.rows||data?.items||data?.signals||[];const[range,setRange]=useState(String(data?.range_days||data?.signalRangeDays||data?.days||1));const[sel,setSel]=useState<S[]>(['新增','刪除','加碼','減碼']);const m=useMemo(()=>{const by=[...rows].sort((a,b)=>flow(b)-flow(a));const sum:any={新增:0,刪除:0,加碼:0,減碼:0};rows.forEach(r=>sum[st(r)]++);return{inflow:by.find(x=>flow(x)>0)||by[0],outflow:[...rows].sort((a,b)=>flow(a)-flow(b)).find(x=>flow(x)<0)||rows[0],mostAdd:[...rows].sort((a,b)=>addc(b)-addc(a)||flow(b)-flow(a))[0],mostReduce:[...rows].sort((a,b)=>redc(b)-redc(a)||flow(a)-flow(b))[0],sum}},[rows]);const shown=rows.filter(r=>sel.includes(st(r)));const fetched=data?.fetched_etf_count??data?.fetchedEtfCount??0,total=data?.total_etf_count??data?.totalEtfCount??fetched;const miss=data?.missing_etfs||data?.missingEtfs||[];return <main className="page v86-page"><section><div className="v86-label">訊號區間</div><div className="v86-seg">{[['1','今日'],['5','5日'],['10','10日'],['20','20日']].map(([v,t])=><button key={v} onClick={()=>setRange(v)} className={range===v?'on':''}>{t}</button>)}</div></section><section className="v86-title"><h1>{range==='1'?'今日':range+'日'}訊號</h1><p>已抓取 {fetched||total||0} / {total||fetched||0} 檔 ETF，資料日期 {ddate(data)||'-'}</p>{Array.isArray(miss)&&miss.length>0&&<mark>⚠️ {miss.length} 檔資料待補：{miss.slice(0,4).join('、')}</mark>}</section><section className="v86-focus-wrap"><Focus title="資金流入最多" item={m.inflow} kind="red"/><Focus title="資金流出最多" item={m.outflow} kind="green"/><Focus title="最多 ETF 加碼" item={m.mostAdd} kind="red"/><Focus title="最多 ETF 減碼" item={m.mostReduce} kind="green"/></section><h2 className="v86-h2">資金交易明細：共 {shown.length} 檔</h2><div className="v86-pills">{(['新增','刪除','加碼','減碼'] as S[]).map(x=><button key={x} onClick={()=>setSel(p=>p.includes(x)?p.filter(v=>v!==x):[...p,x])} className={`${sel.includes(x)?'on':''} ${x}`}>{x} <b>{m.sum[x]}</b></button>)}</div><section className="v86-list">{shown.slice(0,120).map((r,i)=>{const c=code(r),f=flow(r),p=cpct(r),x=st(r);return <Link href={`/stock/${c}?from=signals`} key={c+i} className="v86-row"><div><b>{name(r)}</b><span>{c}</span></div><div><b>{fm(price(r),1)}</b><span className={toneCls(p)}>{pct(p,2)}</span></div><em className={x}>{x}</em><strong className={f>=0?'v86-red':'v86-green'}>{f>=0?'+':''}{fmt(f,2)} 億</strong></Link>})}</section></main>}
