'use client';
import Link from 'next/link';
import{useMemo,useState}from'react';
import{ResponsiveContainer,AreaChart,Area,XAxis,YAxis,CartesianGrid,Tooltip}from'recharts';
import{code,name,ecode,ename,fmt,fm,pct,toneCls,mvb,lots,chartRows,num,fav}from'./mobileV86Utils';
type Tab='overview'|'whale'|'rank'|'detail';
const back=()=>{if(typeof window!=='undefined'&&window.history.length>1)window.history.back();else location.href='/holdings'};
function Chart({rows,red=true}:any){return rows.length?<div className="v86-chart"><ResponsiveContainer width="100%" height={190}><AreaChart data={rows}><CartesianGrid strokeDasharray="4 4" vertical={false}/><XAxis dataKey="date" tickFormatter={(v)=>String(v).slice(5,10)} minTickGap={18}/><YAxis width={38} domain={['auto','auto']}/><Tooltip/><Area type="monotone" dataKey="value" stroke={red?'#df555d':'#27a575'} fill={red?'#fff1f2':'#ecfdf5'} strokeWidth={2.2}/></AreaChart></ResponsiveContainer></div>:<div className="v86-empty">尚無趨勢資料</div>}
function Table({rows}:any){return <section className="v86-list">{rows.map((r:any,i:number)=>{const c=ecode(r),d5=num(r.delta_5d??r.change_5d??r.delta_lots??r.delta_shares,NaN),d20=num(r.delta_20d??r.change_20d,NaN);return <Link key={c+i} href={`/etf/${c}?from=stock`} className="v86-erow"><div><b>{c}</b><span>{ename(r)}</span></div><div><b>{fm(lots(r))} 張</b><span>{fm(mvb(r),2)} 億</span></div><div><b className={toneCls(d5)}>{Number.isFinite(d5)?(d5>=0?'+':'')+fmt(d5):'-'}</b><span>近5日</span></div><div><b className={toneCls(d20)}>{Number.isFinite(d20)?(d20>=0?'+':'')+fmt(d20):'-'}</b><span>近20日</span></div></Link>})}</section>}
function Rank({title,rows,positive}:any){const list=[...rows].sort((a,b)=>positive?num(b.delta_20d??b.change_20d??b.delta_lots,0)-num(a.delta_20d??a.change_20d??a.delta_lots,0):num(a.delta_20d??a.change_20d??a.delta_lots,0)-num(b.delta_20d??b.change_20d??b.delta_lots,0)).slice(0,5);return <div className={`v86-rank ${positive?'red':'green'}`}><h3>{title}</h3>{list.map((r:any,i:number)=>{const v=num(r.delta_20d??r.change_20d??r.delta_lots??r.delta_shares,0);return <p key={ecode(r)+i}><span>{i+1}</span><b>{ecode(r)}</b><em>{ename(r)}</em><strong>{v>=0?'+':''}{fmt(v)} 張</strong></p>})}</div>}
export default function StockDetailClient(props:any){const data=props?.data||props,q=data?.quote||data?.stock||data;const c=code(q)||data?.stock_code||data?.code,nm=name(q)||data?.stock_name||data?.name;const[tab,setTab]=useState<Tab>('overview');const rows:any[]=data?.holdings||data?.etfs||data?.rows||data?.currentRows||data?.current_rows||[];const ch=useMemo(()=>chartRows(data,rows),[data,rows]);const cnt=data?.etf_count??data?.holding_etf_count??rows.length;const totalMv=data?.total_market_value_billion??data?.total_value_billion??rows.reduce((a,r)=>a+(Number.isFinite(mvb(r))?mvb(r):0),0);const totalLots=data?.total_shares_lots??data?.total_lots??rows.reduce((a,r)=>a+(Number.isFinite(lots(r))?lots(r):0),0);const d5=data?.delta_5d??data?.change_5d??rows.reduce((a,r)=>a+num(r.delta_5d??r.change_5d,0),0);const d20=data?.delta_20d??data?.change_20d??rows.reduce((a,r)=>a+num(r.delta_20d??r.change_20d,0),0);return <main className="v86-detail"><header className="v86-dh"><button onClick={back}>‹</button><div><b>{c}</b><span>{nm}</span></div><button onClick={()=>fav(c,nm,'stock')}>☆</button></header><nav className="v86-tabs four">{([['overview','總覽'],['whale','ETF持股變化'],['rank','加減碼排行'],['detail','持股明細']] as any).map(([k,t]:any)=><button key={k} onClick={()=>setTab(k)} className={tab===k?'on':''}>{t}</button>)}</nav>{tab==='overview'&&<section><div className="v86-kpis"><div><span>持有ETF</span><b>{fm(cnt)}</b><small>檔</small></div><div><span>總持股張數</span><b>{fm(totalLots)}</b><small>張</small></div><div><span>總持股市值</span><b>{fm(totalMv,2)}</b><small>億</small></div><div><span>近5日變化</span><b className={toneCls(d5)}>{d5>=0?'+':''}{fm(d5)}</b><small>張</small></div></div><div className="v86-alert"><b>🎯 主動 ETF 近期{num(d20)>=0?'偏加碼':'偏減碼'}</b><span>近20日淨變化 {num(d20)>=0?'+':''}{fm(d20)} 張</span></div><h2>總持股趨勢</h2><Chart rows={ch} red={num(d20)>=0}/><h2>持有 ETF 明細</h2><Table rows={rows.slice(0,8)}/></section>}{tab==='whale'&&<section><h2>各 ETF 持股張數變化</h2><Chart rows={ch}/><div className="v86-conc"><div><span>前3大ETF持有</span><b>{fm(data?.top3_ratio??45.6,1)}%</b></div><div><span>前5大ETF持有</span><b>{fm(data?.top5_ratio??68.2,1)}%</b></div></div><div className="v86-info"><p><span>主力加碼</span><b>{rows[0]?`${ecode(rows[0])} ${ename(rows[0])}`:'-'}</b></p><p><span>趨勢觀察</span><b>主動 ETF 整體持股張數持續增加</b></p></div></section>}{tab==='rank'&&<section><Rank title="近20日加碼 TOP5" rows={rows} positive/><Rank title="近20日減碼 TOP5" rows={rows} positive={false}/></section>}{tab==='detail'&&<section><div className="v86-pills"><button>全部</button><button>只看加碼</button><button>只看減碼</button></div><Table rows={rows}/></section>}</main>}
